//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraUdeCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPERTY()
        {
            this.REQUEST = new HashSet<REQUEST>();
        }
    
        public string CODE { get; set; }
        public string IDENTIFICATION { get; set; }
        public int VALUE { get; set; }
        public bool STATUS { get; set; }
        public string BLOCK { get; set; }
    
        public virtual BLOCK BLOCK1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUEST { get; set; }
    }
}
