//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraUdeCController
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAL_INFORMATION
    {
        public int ID { get; set; }
        public Nullable<int> INCOME_TOTAL { get; set; }
        public string WORK_DATE { get; set; }
        public string TIME_CURRENTE_JOB { get; set; }
        public string FAMILY_REFERENCE_NAME { get; set; }
        public string FAMILY_REFERENCE_PHONE { get; set; }
        public string PERSONAL_REFERENCE { get; set; }
        public string PERSONAL_REFERENCE_PHONE { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
    
        public virtual CUSTOMER CUSTOMER1 { get; set; }
    }
}
