//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraUdeCController
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int ID { get; set; }
        public string CUSTOMER { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
        public int DEBT_TOTAL { get; set; }
        public int PAID_VALUE { get; set; }
        public int TOTAL_SUBSCRIBER { get; set; }
        public int REQUEST { get; set; }
        public int RECEIPT { get; set; }
    
        public virtual RECEIPT RECEIPT1 { get; set; }
        public virtual REQUEST REQUEST1 { get; set; }
    }
}
